version: '3.8'

services:
  # === PostgreSQL для safedeck-root ===
  postgres-root:
    image: postgres:15
    container_name: postgres-root
    environment:
      POSTGRES_USER: root_user
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: root_db
    ports:
      - "5434:5432"  # Чтобы не конфликтовать с другим Postgres
    volumes:
      - postgres_root_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root_user -d root_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # === PostgreSQL для safedeck-encrypt-service ===
  postgres-encrypt:
    image: postgres:15
    container_name: postgres-encrypt
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: encrypt
    ports:
      - "5433:5432"
    volumes:
      - postgres_encrypt_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U encrypt_user -d encrypt_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # === Микросервисы ===

  safedeck-root:
    build:
      context: .
      dockerfile: root/Dockerfile
    container_name: safedeck-root
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-root:5432/root_db
      SPRING_DATASOURCE_USERNAME: root_user
      SPRING_DATASOURCE_PASSWORD: root_pass
    depends_on:
      postgres-root:
        condition: service_healthy

  safedeck-email-service:
    build:
      context: .
      dockerfile: safedeck-email-service/Dockerfile
    container_name: safedeck-email-service
    ports:
      - "8087:8087"

  safedeck-encrypt-service:
    build:
      context: .
      dockerfile: safedeck-encrypt-service/Dockerfile
    container_name: safedeck-encrypt-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-encrypt:5432/encrypt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      postgres-encrypt:
        condition: service_healthy

  safedeck-llm-service:
    build:
      context: .
      dockerfile: safedeck-llm/Dockerfile
    container_name: safedeck-llm-service
    ports:
      - "8082:8082"

volumes:
  postgres_encrypt_data:
  postgres_root_data: