server:
  port: 8090

springdoc:
  swagger-ui:
    enabled: true
  openapi:
    urls:
      - /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  security:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/root_db
    username: root_user
    password: root_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/main-changelog.xml