FROM python:3.11-slim

# Установка зависимостей
WORKDIR /code
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Создание пользователя
RUN useradd --create-home --shell /bin/bash user

# Настройка рабочей директории
WORKDIR /home/user/app
COPY --chown=user:user . .

# Запуск от пользователя
USER user

# Убедитесь, что uvicorn указан как uvicorn[standard] в requirements.txt
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]